//
//  Protocol+Generatable.swift
//  obs-ws-swift
//
//  Created by Edon Valdman on 5/18/26.
//

import Foundation
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftBasicFormat

extension OBSWSProtocol: Generatable {
    private var format: BasicFormat {
        .init(indentationWidth: .spaces(2))
    }
    
    // Using leading newline + trailing newline:
    // For the 1st decl, leading newline moves it to its own line without an extra empty line before
    // For the 2nd decl, it adds to the previous's decl trailing newline, giving an extra empty line between
    
    private var sourceFileHeaderComment: Trivia {
        .blockComment(
            """
            /**
             * This file is autogenerated. Do not edit.
             */
            """
        )
        .appending(.newline)
    }
    
    private var namespaceEnumComment: Trivia {
        .docLineComment("/// Namespace for all generated OBS WebSocket types.")
        .appending(.newline)
    }
    
    func generate() throws -> SourceFileSyntax {
        try SourceFileSyntax(leadingTrivia: sourceFileHeaderComment) {
            try ImportDeclSyntax("import Foundation")
                .with(\.leadingTrivia, .newline)
                .with(\.trailingTrivia, .newline)
            try ImportDeclSyntax("import JSONValue")
                .with(\.trailingTrivia, .newline)
            
            try ExtensionDeclSyntax("public extension OBS") {
                try EnumDeclSyntax("public enum Enums") {
                    for enumDef in self.enums {
                        try enumDef.generate()
                            .prepending(.newline, to: \.leadingTrivia)
                            .appending(.newline, to: \.trailingTrivia)
                    }
                }
                .with(\.leadingTrivia, .newline)
                .with(\.trailingTrivia, .newline)
                
                try EnumDeclSyntax("public enum Requests") {
                    for reqDef in self.requests {
                        try reqDef.generate()
                            .prepending(.newline, to: \.leadingTrivia)
                            .appending(.newline, to: \.trailingTrivia)
                    }
                    
                    try requestsAllTypesEnum()
                }
                .with(\.leadingTrivia, .newline)
                .with(\.trailingTrivia, .newline)
                
                try EnumDeclSyntax("public enum Events") {
                    for eventDef in self.events {
                        try eventDef.generate()
                            .prepending(.newline, to: \.leadingTrivia)
                            .appending(.newline, to: \.trailingTrivia)
                    }
                    
                    try eventsAllTypesEnum()
                }
                .with(\.leadingTrivia, .newline)
                .with(\.trailingTrivia, .newline)
            }
            .with(
                \.leadingTrivia,
                 .newline
                    .appending(namespaceEnumComment)
            )
            .with(\.trailingTrivia, .newline)
        }
        .formatted(using: format)
        .as(SourceFileSyntax.self)!
    }
    
    private func requestsAllTypesEnum() throws -> EnumDeclSyntax {
        try EnumDeclSyntax("public enum AllTypes: String, CaseIterable, Sendable, Hashable, Codable") {
            for reqDef in self.requests {
                try EnumCaseDeclSyntax("case \(raw: reqDef.requestType)")
                    .appending(.newline, to: \.trailingTrivia)
            }
            
            let functionParamList = FunctionParameterListSyntax {
                FunctionParameterSyntax("ofType type: AllTypes, ")
                FunctionParameterSyntax("from requestData: JSONValue")
            }
            
            try FunctionDeclSyntax("static func request(\(functionParamList)) throws -> (any OBSRequest)?") {
                try SwitchExprSyntax("switch type") {
                    for reqDef in self.requests {
                        SwitchCaseSyntax("case .\(raw: reqDef.requestType):") {
                            CodeBlockItemSyntax("return try requestData.toCodable(OBS.Requests.\(raw: reqDef.requestType).self)")
                                .with(\.leadingTrivia, .newline)
                        }
                        .with(\.leadingTrivia, .newline)
                    }
                }
                .with(\.leadingTrivia, .newline)
                .with(\.trailingTrivia, .newline)
            }
            .with(\.leadingTrivia, .newline)
            .with(\.trailingTrivia, .newline)
        }
        .with(\.leadingTrivia, .newline)
        .with(\.trailingTrivia, .newline)
    }
    
    private func eventsAllTypesEnum() throws -> EnumDeclSyntax {
        try EnumDeclSyntax("public enum AllTypes: String, CaseIterable, Sendable, Hashable, Codable") {
            for eventDef in self.events {
                try EnumCaseDeclSyntax("case \(raw: eventDef.eventType)")
                    .appending(.newline, to: \.trailingTrivia)
            }
            
            let functionParamList = FunctionParameterListSyntax {
                FunctionParameterSyntax("ofType type: AllTypes, ")
                FunctionParameterSyntax("from eventData: JSONValue")
            }
            
            try FunctionDeclSyntax("static func event(\(functionParamList)) throws -> (any OBSEvent)?") {
                try SwitchExprSyntax("switch type") {
                    for eventDef in self.events {
                        SwitchCaseSyntax("case .\(raw: eventDef.eventType):") {
                            CodeBlockItemSyntax("return try eventData.toCodable(OBS.Events.\(raw: eventDef.eventType).self)")
                                .with(\.leadingTrivia, .newline)
                        }
                        .with(\.leadingTrivia, .newline)
                    }
                }
                .with(\.leadingTrivia, .newline)
                .with(\.trailingTrivia, .newline)
            }
            .with(\.leadingTrivia, .newline)
            .with(\.trailingTrivia, .newline)
        }
        .with(\.leadingTrivia, .newline)
        .with(\.trailingTrivia, .newline)
    }
}
